services:
  app:
    build: .
    ports:
      - "4300:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "6671:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
